name: pansr
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7.12
    - scikit-learn=0.24.1
    - pandas=1.3.5
    - numpy=1.21.6
    - jupyter
    - joblib
    - sympy
    - pyyaml
    - pyarrow
    - pip
    - pip:
        - pmlb==1.0.1.post3
        - rpy2
