name: pansr
channels:
    - conda-forge
dependencies:
    - python=3.7.*
    - cmake=3.19.1 # operon, feat
    - eigen=3.3.9 # operon, feat, ellyn
    - boost=1.74.0 # gpgomea, ellyn
    - pkg-config # gpgomea
    - joblib=1.3.2
    - scikit-learn=0.24.1 
    - pyarrow
    - pandas 
    - numpy=1.21.6
    - gplearn
    - jupyter
    - pytest
    # operon 
    - pybind11=2.6.1 
    - fmt=7.1.3 
    - taskflow=3.3.0
    - xxhash
    - ceres-solver=2.0.0
    - cxxopts
    - optuna
    # deep-symbolic-regression 
    - tensorflow=1.14 
    - cython
    - numba
    - sympy
    - click
    - mpi4py
    - dataclasses
    - deap
    # feat
    - cython=0.29.*
    - ninja
    - setuptools=45.*
    - shogun-cpp=6.1.4
    - wheel=0.35.*
    - openlibm
    - pip
    - pip:
        - DistanceClassifier==0.0.8 # ellyn
        - pmlb==1.0.1.post3
        - rpy2
        # ffx
        - git+https://github.com/lacava/ffx 
        - eigency==1.77
        # BSR
        - git+https://github.com/lacava/MCMC-SymReg
        # AI-feynman
        - git+https://github.com/lacava/AI-Feynman
