name: pansr_pysr
channels:
  - defaults
dependencies:
  - python=3.8.18
  - joblib
  - jupyter
  - pytest
  - setuptools=68.2.2
  - yaml=0.2.5
  - pyarrow=11.0.0
  - pip
  - pip:
      - click==8.1.7
      - numpy==1.24.4
      - pandas==2.0.3
      - pysr==0.16.9
      - pyyaml==6.0.1
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sympy==1.12
      - rpy2
