name: pansr_udsr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.12
  - joblib
  - jupyter
  - gast=0.2.2
  - pandas=1.3.5
  - pytest=7.1.2
  - pyyaml=6.0
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - sympy=1.10.1
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - yaml=0.2.5
  - pip
  - pip:
      - click==8.1.3
      - commentjson==0.9.0
      - cython==0.29.28
      - deap==1.3.1
      - numba==0.53.1
      - numpy==1.19.0
      - pathos==0.2.8
      - prettytable==3.3.0
      - progress==1.6
      - pyarrow==12.0.1
      - pytest-order==1.2.0
      - seaborn==0.11.2
      - tqdm==4.64.0
      - rpy2
